### ISSUE TITLE
Upgrades broken

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/mysql-router-operator#130]
Upgrades broken by #93

Calls to `workload.enable()` and `workload.disable()` appear on main
https://github.com/canonical/mysql-router-operator/blob/557f884d9173b32d6f1630633f7a966c646ed0c1/src/workload.py#L398-L402

but `workload.enable()` and `workload.disable()` removed in #93

Causes error:
```
unit-mysql-router-2: 11:25:29 ERROR unit.mysql-router/2.juju-log upgrade-version-a:5: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/./src/machine_charm.py", line 117, in <module>
    ops.main.main(MachineSubordinateRouterCharm)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/src/abstract_charm.py", line 252, in reconcile
    self._upgrade.upgrade_unit(
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/src/machine_upgrade.py", line 150, in upgrade_unit
    workload_.upgrade(unit=self._unit, tls=tls)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/src/workload.py", line 398, in upgrade
    self.disable()
AttributeError: 'AuthenticatedSocketWorkload' object has no attribute 'disable'
```

**Comment by shayancanonical** [comment]
resolved in https://github.com/canonical/mysql-router-operator/pull/119 and added tests in https://github.com/canonical/mysql-router-operator/pull/135
